services:
  db:
    container_name: postgres-backend
    image: postgres:16.3
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - db
    restart: unless-stopped

  backend-api:
    container_name: backend
    image: chrzanekk/backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: password
    expose:
      - "8080"
    networks:
      - db
    depends_on:
      - db

  frontend-react:
    container_name: frontend-react
    image: chrzanekk/frontend-react
    build:
      context: frontend/react
      args:
        api_base_url: http://backend-api:8080
    expose:
      - "80"
    depends_on:
      - backend-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: