services:
  db:
    container_name: postgres-backend
    image: postgres:16.3
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
#      PGDATA: /data/postgres
    volumes:
#      - db:/data/postgres
      - db-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - app-network
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
#    image: chrzanekk/backend:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  frontend-react:
    image: chrzanekk/frontend-react
#    build:
#      context: ./frontend/react
#      dockerfile: Dockerfile
#      args:
#        api_base_url: http://backend-api:8080
    ports:
      - "3000:5173"
    depends_on:
      - backend-api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
#    driver: bridge

volumes:
  db-data: