services:
  db:
    container_name: postgres-backend
    image: postgres:16.3
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - app-network
    restart: unless-stopped

  backend-api:
    image: chrzanekk/backend:latest
    container_name: backend-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  frontend-react:
    image: chrzanekk/frontend-react:latest
    container_name: frontend-react
    ports:
      - "5173:80"
    depends_on:
      - backend-api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  db: