services:
  db:
    container_name: postgres-backend
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5444:5432"
    networks:
      - db
    restart: unless-stopped

  backend-api:
    container_name: backend
    image: chrzanekk/backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: