name: CD - Deploy React Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/react/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        working-directory: ./frontend/react
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-react:latest \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-react:latest

      - name: Upload docker-compose.yml to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ./docker-compose.yml
          target: /home/debian/app

      - name: SSH into VPS and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/debian/app
            docker-compose pull frontend-react
            docker-compose up -d frontend-react